name: Scoring code quality

on:
  push:
    branches:
      - feedback
  workflow_dispatch:

jobs:
  score-code:
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        os: ["ubuntu", "windows", "macos"]
    continue-on-error: true

    steps:

    - uses: actions/checkout@v2

    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-version: latest
        environment-file: environment.yml
        activate-environment: daps-final
        auto-activate-base: false

    - name: Check code quality
      id: linting
      run: |
        pip install pylint
        MESSAGE=$(pylint -ry $(git ls-files '*.py') ||:)

        echo 'MESSAGE<<EOF' >> $GITHUB_ENV
        echo "<pre><code>$MESSAGE</code></pre>" >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV

        echo "Printing PR message: $MESSAGE"

    - name: Post report to pull request
      uses: mshick/add-pr-comment@v2
      with:
        issue: 1
        message: ${{ env.MESSAGE }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Check for reproducibility
      run: |
        conda info --envs
        conda env list
        conda list
        python main.py